# Introduction

this dataset from https://www.kaggle.com/datasets/deepcontractor/car-price-prediction-challenge

# Question
### 1-What is the maximum price of a car in the dataset?
### 2-What is the minimum price of a car in the dataset?
### 3-What is the average price of cars in the dataset?
### 4-How many cars have leather interior?
### 5-What is the most common category of cars in the dataset?
### 6-What is the least common category of cars in the dataset?*
### 7-What is the average mileage of cars in the dataset?
### 8-What is the maximum engine volume in the dataset?
### 9-What is the maximum levy of a car in the dataset?
### 10-What is the min levy of a car in the dataset?
### 11-What is the average levy of cars in the dataset?
### 12-What is the most common manufaeturer of cars in the dataset?
### 13-What is the least common manufaeturer of cars in the dataset?*
### 14-What is the most common model of cars in the dataset?
### 15-What is the least common model of cars in the dataset?
### 16-What is the most common wheel of cars in the dataset?
### 17-What is the most common model of color in the dataset?
### 18-What is the least common model of color in the dataset?
### 19-What is the average airbags of cars in the dataset?
### 20-What is the most common fuel type of color in the dataset?
### 21-What is the least common fuel type of color in the dataset?
### 22-What is the average mileage of cars in the dataset?
### 23-correlations between engine volem and price
### 24-correlations between cylinder and price
### 25-correlations between airbagr and price
### 26-correlations between drive whells and price
### 27-correlations between gear box and price 
### 28-correlations between mile and price 
### 29-What is the most common girbox in the dataset?
### 30-What is the least common girbox in the dataset
### 31-What is the most common drive wheels  in the dataset?
### 32-What is the least common drive wheels in the dataset
### 33-What is the average engine volume of cars with 4 cylinders?
### 34-How many cars have a price higher than the average price in the dataset?
### 35-What is the average price of cars with a fuel type of 'Hybrid'?
### 36-What is the average price of cars produced after the year 2015?
### 37-How many cars have a price between $10,000 and $20,000?
### 38-What is the average mileage of cars produced in the year 2018?
### 39-What is the average price of cars with a 'Category' value of 'Sedan'?
### 40-What is the average price of cars with a 'Drive wheels' value of '4x4'
### 41-What is the most common manufacturer for cars with a 'Category' value of 'Hatchback'?
### 42-What is the average price of cars with a 'Model' value of 'Corolla'?
### 43-What is the average mileage of cars with a 'Category' value of 'jeep'?
### 44-What is the average price of cars with a 'Manufacturer' of 'Lexus' and 'Engine volume' greater than 3.5?
### 45-How many cars have a 'Category' of 'Hatchback' and 'Airbags' greater than 4?
### 46-What is the average mileage of cars with a 'Manufacturer' of 'Honda' and 'Model' of 'Civic'?
### 47-How many cars have a 'Manufacturer' of 'Ford' and 'Airbags' less than or equal to 4?

# Import library

In [84]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
import copy
import math
from pandas.plotting import scatter_matrix

In [85]:
data = pd.read_csv('car_price_prediction.csv')
data

ID  Price         Levy   Manufacturer    Model  Prod. year  \
0      45654403  13328  1399.000000          LEXUS   RX 450        2010   
1      44731507  16621  1018.000000      CHEVROLET  Equinox        2011   
2      45774419   8467   906.299205          HONDA      FIT        2006   
3      45769185   3607   862.000000           FORD   Escape        2011   
4      45809263  11726   446.000000          HONDA      FIT        2014   
...         ...    ...          ...            ...      ...         ...   
16356  45772306   5802  1055.000000  MERCEDES-BENZ    E 350        2013   
16357  45778856  15681   831.000000        HYUNDAI   Sonata        2011   
16358  45804997  26108   836.000000        HYUNDAI   Tucson        2010   
16359  45793526   5331  1288.000000      CHEVROLET  Captiva        2007   
16360  45813273    470   753.000000        HYUNDAI   Sonata        2012   

        Category Leather interior Fuel type  Engine volume  Mileage  \
0           Jeep              Yes    Hybrid            3.5   186005   
1           Jeep               No    Petrol            3.0   192000   
2      Hatchback               No    Petrol            1.3   200000   
3           Jeep              Yes    Hybrid            2.5   168966   
4      Hatchback              Yes    Petrol            1.3    91901   
...          ...              ...       ...            ...      ...   
16356      Sedan              Yes    Diesel            3.5   107800   
16357      Sedan              Yes    Petrol            2.4   161600   
16358       Jeep              Yes    Diesel            2.0   116365   
16359       Jeep              Yes    Diesel            2.0    51258   
16360      Sedan              Yes    Hybrid            2.4   186923   

       Cylinders Gear box type Drive wheels  Doors             Wheel   Color  \
0              6     Automatic          4x4      4        Left wheel  Silver   
1              6     Tiptronic          4x4      4        Left wheel   Black   
2              4      Variator        Front      4  Right-hand drive   Black   
3              4     Automatic          4x4      4        Left wheel   White   
4              4     Automatic        Front      4        Left wheel  Silver   
...          ...           ...          ...    ...               ...     ...   
16356          6     Automatic         Rear      4        Left wheel    Grey   
16357          4     Tiptronic        Front      4        Left wheel     Red   
16358          4     Automatic        Front      4        Left wheel    Grey   
16359          4     Automatic        Front      4        Left wheel   Black   
16360          4     Automatic        Front      4        Left wheel   White   

       Airbags  has_turbo  
0           12      False  
1            8      False  
2            2      False  
3            0      False  
4            4      False  
...        ...        ...  
16356       12      False  
16357        8      False  
16358        4      False  
16359        4      False  
16360       12      False  

[16361 rows x 19 columns]

In [86]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16361 entries, 0 to 16360
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   ID                16361 non-null  int64  
 1   Price             16361 non-null  int64  
 2   Levy              16361 non-null  float64
 3   Manufacturer      16361 non-null  object 
 4   Model             16361 non-null  object 
 5   Prod. year        16361 non-null  int64  
 6   Category          16361 non-null  object 
 7   Leather interior  16361 non-null  object 
 8   Fuel type         16361 non-null  object 
 9   Engine volume     16361 non-null  float64
 10  Mileage           16361 non-null  int64  
 11  Cylinders         16361 non-null  int64  
 12  Gear box type     16361 non-null  object 
 13  Drive wheels      16361 non-null  object 
 14  Doors             16361 non-null  int64  
 15  Wheel             16361 non-null  object 
 16  Color             16361 non-null  object

In [87]:
data.isnull().sum()

ID                  0
Price               0
Levy                0
Manufacturer        0
Model               0
Prod. year          0
Category            0
Leather interior    0
Fuel type           0
Engine volume       0
Mileage             0
Cylinders           0
Gear box type       0
Drive wheels        0
Doors               0
Wheel               0
Color               0
Airbags             0
has_turbo           0
dtype: int64

## Handling Duplicating

In [88]:
data.shape

(16361, 19)

In [89]:
data.drop_duplicates(inplace=True)

In [90]:
data.shape

(16361, 19)

In [91]:
data.duplicated().sum()

0

# Exploring my column

In [92]:
data['Price'].unique()

array([13328, 16621,  8467, ..., 17042, 18779, 22075])

In [93]:
data['Levy'].unique()

array([ 1399.        ,  1018.        ,   906.29920545,   862.        ,
         446.        ,   891.        ,   761.        ,   751.        ,
        1053.        ,  1055.        ,  1079.        ,   810.        ,
        2386.        ,  1850.        ,   531.        ,   586.        ,
        1249.        ,  2455.        ,   583.        ,  1288.        ,
         915.        ,  1750.        ,   707.        ,  1486.        ,
        1091.        ,   650.        ,   382.        ,  1436.        ,
        1194.        ,   503.        ,  1104.        ,  1017.        ,
         639.        ,   629.        ,   919.        ,   781.        ,
         530.        ,   640.        ,   777.        ,   779.        ,
         934.        ,   769.        ,   645.        ,  1185.        ,
        1324.        ,   830.        ,  1187.        ,  1111.        ,
         760.        ,   642.        ,  1095.        ,   966.        ,
         473.        ,  1138.        ,  1811.        ,   988.        ,
      

In [94]:
data['Manufacturer'].unique()

array(['LEXUS', 'CHEVROLET', 'HONDA', 'FORD', 'HYUNDAI', 'TOYOTA',
       'MERCEDES-BENZ', 'PORSCHE', 'BMW', 'JEEP', 'VOLKSWAGEN', 'AUDI',
       'RENAULT', 'NISSAN', 'SUBARU', 'DAEWOO', 'KIA', 'MITSUBISHI',
       'SSANGYONG', 'MAZDA', 'GMC', 'FIAT', 'INFINITI', 'ALFA ROMEO',
       'SUZUKI', 'OPEL', 'ACURA', 'CITROEN', 'MINI', 'DODGE', 'CHRYSLER',
       'ISUZU', 'VAZ', 'JAGUAR', 'SKODA', 'LINCOLN', 'DAIHATSU', 'BUICK',
       'CADILLAC', 'PEUGEOT', 'VOLVO', 'სხვა', 'HAVAL', 'LAND ROVER',
       'SCION', 'MERCURY', 'SEAT', 'LANCIA', 'MASERATI', 'HUMMER', 'SAAB',
       'GAZ', 'UAZ', 'PONTIAC', 'SATURN', 'GREATWALL'], dtype=object)

In [95]:
data['Model'].unique()

array(['RX 450', 'Equinox', 'FIT', ..., '406', 'Prius C aqua',
       'Optima ex'], dtype=object)

In [96]:
data['Prod. year'].unique()

array([2010, 2011, 2006, 2014, 2016, 2013, 2007, 2018, 2008, 2012, 2017,
       2001, 2000, 2015, 2004, 2009, 2019, 2005, 2003, 2002, 2020])

In [97]:
data['Category'].unique()

array(['Jeep', 'Hatchback', 'Sedan', 'Microbus', 'Goods wagon',
       'Universal', 'Coupe', 'Minivan', 'Cabriolet', 'Pickup',
       'Limousine'], dtype=object)

In [98]:
data['Leather interior'].unique()

array(['Yes', 'No'], dtype=object)

In [99]:
data['Fuel type'].unique()

array(['Hybrid', 'Petrol', 'Diesel', 'Plug-in Hybrid', 'CNG', 'LPG',
       'Hydrogen'], dtype=object)

In [100]:
data['Engine volume'].unique()

array([ 3.5,  3. ,  1.3,  2.5,  2. ,  1.8,  2.4,  3.3,  1.6,  2.2,  4.7,
        1.5,  4.4,  1.4,  3.6,  4. ,  2.3,  3.2,  3.8,  4.6,  1.2,  5. ,
        1.7,  2.9,  0.5,  1.9,  5.5,  5.3,  0.4,  2.8,  2.1,  0.7,  4.8,
        2.7,  3.7,  1. ,  2.6,  0.8,  0.2,  5.7,  6.7,  6.2,  3.4,  4.2,
       20. ,  1.1,  0. ,  5.6,  0.6,  4.5,  7.3,  0.1,  5.4,  4.3,  6.4,
        3.9,  5.9,  6.3,  6. ,  0.3,  5.2,  5.8])

In [101]:
data['Mileage'].unique()

array([186005, 192000, 200000, ..., 140607, 307325, 186923])

In [102]:
data['Cylinders'].unique()

array([ 6,  4,  8, 12, 16,  5, 10,  7, 14])

In [103]:
data['Gear box type'].unique()

array(['Automatic', 'Tiptronic', 'Variator', 'Manual'], dtype=object)

In [104]:
data['Drive wheels'].unique()

array(['4x4', 'Front', 'Rear'], dtype=object)

In [105]:
data['Doors'].unique()

array([4, 2, 5])

In [106]:
data['Wheel'].unique()

array(['Left wheel', 'Right-hand drive'], dtype=object)

In [107]:
data['Color'].unique()

array(['Silver', 'Black', 'White', 'Grey', 'Blue', 'Sky blue', 'Red',
       'Green', 'Yellow', 'Brown', 'Golden', 'Beige', 'Orange',
       'Carnelian red', 'Purple', 'Pink'], dtype=object)

In [108]:
data['Airbags'].unique()

array([12,  8,  2,  0,  4,  6, 10,  3,  1, 16,  7,  9,  5, 11, 14, 15, 13])

### fix Levy

In [109]:
data['Levy'].value_counts()

906.299205     4433
640.000000      392
639.000000      326
891.000000      323
765.000000      314
               ... 
3329.000000       1
1553.000000       1
916.000000        1
3008.000000       1
1901.000000       1
Name: Levy, Length: 504, dtype: int64

In [110]:
data['Levy'].replace({'-':np.nan}, inplace=True)

In [111]:
data['Levy'] = data['Levy'].astype(float)

In [112]:
data.head()

ID  Price         Levy Manufacturer    Model  Prod. year   Category  \
0  45654403  13328  1399.000000        LEXUS   RX 450        2010       Jeep   
1  44731507  16621  1018.000000    CHEVROLET  Equinox        2011       Jeep   
2  45774419   8467   906.299205        HONDA      FIT        2006  Hatchback   
3  45769185   3607   862.000000         FORD   Escape        2011       Jeep   
4  45809263  11726   446.000000        HONDA      FIT        2014  Hatchback   

  Leather interior Fuel type  Engine volume  Mileage  Cylinders Gear box type  \
0              Yes    Hybrid            3.5   186005          6     Automatic   
1               No    Petrol            3.0   192000          6     Tiptronic   
2               No    Petrol            1.3   200000          4      Variator   
3              Yes    Hybrid            2.5   168966          4     Automatic   
4              Yes    Petrol            1.3    91901          4     Automatic   

  Drive wheels  Doors             Wheel   Color  Airbags  has_turbo  
0          4x4      4        Left wheel  Silver       12      False  
1          4x4      4        Left wheel   Black        8      False  
2        Front      4  Right-hand drive   Black        2      False  
3          4x4      4        Left wheel   White        0      False  
4        Front      4        Left wheel  Silver        4      False

In [113]:
data.isnull().sum()

ID                  0
Price               0
Levy                0
Manufacturer        0
Model               0
Prod. year          0
Category            0
Leather interior    0
Fuel type           0
Engine volume       0
Mileage             0
Cylinders           0
Gear box type       0
Drive wheels        0
Doors               0
Wheel               0
Color               0
Airbags             0
has_turbo           0
dtype: int64

In [114]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 16361 entries, 0 to 16360
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   ID                16361 non-null  int64  
 1   Price             16361 non-null  int64  
 2   Levy              16361 non-null  float64
 3   Manufacturer      16361 non-null  object 
 4   Model             16361 non-null  object 
 5   Prod. year        16361 non-null  int64  
 6   Category          16361 non-null  object 
 7   Leather interior  16361 non-null  object 
 8   Fuel type         16361 non-null  object 
 9   Engine volume     16361 non-null  float64
 10  Mileage           16361 non-null  int64  
 11  Cylinders         16361 non-null  int64  
 12  Gear box type     16361 non-null  object 
 13  Drive wheels      16361 non-null  object 
 14  Doors             16361 non-null  int64  
 15  Wheel             16361 non-null  object 
 16  Color             16361 non-null  object

### Handling missing value in Levy

In [115]:
Levy = data['Levy']

In [116]:
Levy.head()

0    1399.000000
1    1018.000000
2     906.299205
3     862.000000
4     446.000000
Name: Levy, dtype: float64

In [117]:
Levy_mean = Levy.mean()
Levy_mean

895.263393298243

In [118]:
Levy.fillna(Levy_mean , inplace=True)

In [119]:
Levy.isnull().sum()

0

In [120]:
# data.drop(columns=['Levy'], inplace=True)

## fix Cylinders

In [121]:
data.head()

ID  Price         Levy Manufacturer    Model  Prod. year   Category  \
0  45654403  13328  1399.000000        LEXUS   RX 450        2010       Jeep   
1  44731507  16621  1018.000000    CHEVROLET  Equinox        2011       Jeep   
2  45774419   8467   906.299205        HONDA      FIT        2006  Hatchback   
3  45769185   3607   862.000000         FORD   Escape        2011       Jeep   
4  45809263  11726   446.000000        HONDA      FIT        2014  Hatchback   

  Leather interior Fuel type  Engine volume  Mileage  Cylinders Gear box type  \
0              Yes    Hybrid            3.5   186005          6     Automatic   
1               No    Petrol            3.0   192000          6     Tiptronic   
2               No    Petrol            1.3   200000          4      Variator   
3              Yes    Hybrid            2.5   168966          4     Automatic   
4              Yes    Petrol            1.3    91901          4     Automatic   

  Drive wheels  Doors             Wheel   Color  Airbags  has_turbo  
0          4x4      4        Left wheel  Silver       12      False  
1          4x4      4        Left wheel   Black        8      False  
2        Front      4  Right-hand drive   Black        2      False  
3          4x4      4        Left wheel   White        0      False  
4        Front      4        Left wheel  Silver        4      False

In [122]:
def CL(a):
        if(a<4):
            return np.nan
        else:
            return(a)

CL(6)
CL(1)
CL(3) 

nan

In [123]:
data['Cylinders']=data['Cylinders'].apply(CL)

In [124]:
data['Cylinders'].unique()

array([ 6,  4,  8, 12, 16,  5, 10,  7, 14])

In [125]:
data['Cylinders'].value_counts()

4     12535
6      2868
8       764
5       149
12       27
10       10
16        5
7         2
14        1
Name: Cylinders, dtype: int64

In [126]:
data.isnull().sum()

ID                  0
Price               0
Levy                0
Manufacturer        0
Model               0
Prod. year          0
Category            0
Leather interior    0
Fuel type           0
Engine volume       0
Mileage             0
Cylinders           0
Gear box type       0
Drive wheels        0
Doors               0
Wheel               0
Color               0
Airbags             0
has_turbo           0
dtype: int64

In [127]:
Cylinders_mean = data['Cylinders'].mean()
Cylinders_mean.astype(int)

4

In [128]:
data['Cylinders'].fillna(Cylinders_mean,inplace=True)


In [129]:
data.head()

ID  Price         Levy Manufacturer    Model  Prod. year   Category  \
0  45654403  13328  1399.000000        LEXUS   RX 450        2010       Jeep   
1  44731507  16621  1018.000000    CHEVROLET  Equinox        2011       Jeep   
2  45774419   8467   906.299205        HONDA      FIT        2006  Hatchback   
3  45769185   3607   862.000000         FORD   Escape        2011       Jeep   
4  45809263  11726   446.000000        HONDA      FIT        2014  Hatchback   

  Leather interior Fuel type  Engine volume  Mileage  Cylinders Gear box type  \
0              Yes    Hybrid            3.5   186005          6     Automatic   
1               No    Petrol            3.0   192000          6     Tiptronic   
2               No    Petrol            1.3   200000          4      Variator   
3              Yes    Hybrid            2.5   168966          4     Automatic   
4              Yes    Petrol            1.3    91901          4     Automatic   

  Drive wheels  Doors             Wheel   Color  Airbags  has_turbo  
0          4x4      4        Left wheel  Silver       12      False  
1          4x4      4        Left wheel   Black        8      False  
2        Front      4  Right-hand drive   Black        2      False  
3          4x4      4        Left wheel   White        0      False  
4        Front      4        Left wheel  Silver        4      False

In [130]:
data.isnull().sum()

ID                  0
Price               0
Levy                0
Manufacturer        0
Model               0
Prod. year          0
Category            0
Leather interior    0
Fuel type           0
Engine volume       0
Mileage             0
Cylinders           0
Gear box type       0
Drive wheels        0
Doors               0
Wheel               0
Color               0
Airbags             0
has_turbo           0
dtype: int64

### fix doors

In [131]:
data['Doors'].value_counts()

4    15720
2      542
5       99
Name: Doors, dtype: int64

In [132]:
data['Doors'].replace({'04-May':4, '02-Mar':2, '>5':5}, inplace=True)

In [133]:
data.head()

ID  Price         Levy Manufacturer    Model  Prod. year   Category  \
0  45654403  13328  1399.000000        LEXUS   RX 450        2010       Jeep   
1  44731507  16621  1018.000000    CHEVROLET  Equinox        2011       Jeep   
2  45774419   8467   906.299205        HONDA      FIT        2006  Hatchback   
3  45769185   3607   862.000000         FORD   Escape        2011       Jeep   
4  45809263  11726   446.000000        HONDA      FIT        2014  Hatchback   

  Leather interior Fuel type  Engine volume  Mileage  Cylinders Gear box type  \
0              Yes    Hybrid            3.5   186005          6     Automatic   
1               No    Petrol            3.0   192000          6     Tiptronic   
2               No    Petrol            1.3   200000          4      Variator   
3              Yes    Hybrid            2.5   168966          4     Automatic   
4              Yes    Petrol            1.3    91901          4     Automatic   

  Drive wheels  Doors             Wheel   Color  Airbags  has_turbo  
0          4x4      4        Left wheel  Silver       12      False  
1          4x4      4        Left wheel   Black        8      False  
2        Front      4  Right-hand drive   Black        2      False  
3          4x4      4        Left wheel   White        0      False  
4        Front      4        Left wheel  Silver        4      False

In [134]:
data['Doors'].unique()

array([4, 2, 5])

### fix  Mileage

In [135]:
data['Mileage'].value_counts()

0         559
200000    144
150000    139
160000    112
180000    103
         ... 
56261       1
67381       1
92891       1
67357       1
186923      1
Name: Mileage, Length: 6714, dtype: int64

In [136]:
data['Mileage']=data['Mileage'].str.split(' ').str.get(0)

AttributeError: Can only use .str accessor with string values!

In [ ]:
data['Mileage']=data['Mileage'].astype(int)
data["Mileage"].head()


In [ ]:
data.head()

### fix Engine volume

In [ ]:
data['Engine volume'].value_counts()

In [ ]:
data['Engine volume'] = data['Engine volume'].str.lower()
data["has_turbo"] = data["Engine volume"].str.contains("turbo")

In [ ]:
data['Engine volume']=data['Engine volume'].str.split(' ').str.get(0)

In [ ]:
data['Engine volume']=data['Engine volume'].astype(float)
data["Engine volume"].head()

In [ ]:
data.head()

In [ ]:
data.head()

In [ ]:
data.info()

In [ ]:
data['Cylinders']=data['Cylinders'].astype(int)

In [ ]:
data.head()

In [ ]:
data.describe()

In [ ]:
column_to_analyze = 'Price'

# Define the function to extract the values of outliers using IQR for the specified column
def get_outliers_iqr(data, column):
    Q1 = data[column].quantile(0.25)
    Q3 = data[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    outliers = data[(data[column] < lower_bound) | (data[column] > upper_bound)]
    return outliers[column].values

# Extract the values of outliers in the specified column using IQR
column_outliers = get_outliers_iqr(data, column_to_analyze)

# Print the values of outliers
print("Outliers in", column_to_analyze, ":\n", column_outliers)

# #import libraries
# import numpy as np
# mean = np.mean(data['Price'])
# std = np.std(data['Price'])
# print('mean of the price is', mean)
# print('std. deviation is', std)
# threshold = 3
# outlier = []
# for i in data['Price']:
#     z = (i-mean)/std
#     if z > threshold:
#         outlier.append(i)
# print('outlier in dataset is', outlier)

In [ ]:
column_to_analyze = 'Price'

# Define the function to remove outliers using IQR for the specified column
def remove_outliers_iqr(data, column):
    Q1 = data[column].quantile(0.25)
    Q3 = data[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    return data[(data[column] >= lower_bound) & (data[column] <= upper_bound)]

# Remove outliers from the specified column using IQR
data = remove_outliers_iqr(data, column_to_analyze)

# Print the dataset without outliers in the specified column
print("Dataset without outliers in", column_to_analyze, ":\n", data)

In [ ]:
data.describe()

In [ ]:
column_to_analyze = 'Mileage'

# Define the function to extract the values of outliers using IQR for the specified column
def get_outliers_iqr(data, column):
    Q1 = data[column].quantile(0.25)
    Q3 = data[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    outliers = data[(data[column] < lower_bound) | (data[column] > upper_bound)]
    return outliers[column].values

# Extract the values of outliers in the specified column using IQR
column_outliers = get_outliers_iqr(data, column_to_analyze)

# Print the values of outliers
print("Outliers in", column_to_analyze, ":\n", column_outliers)

In [ ]:
column_to_analyze = 'Mileage'

# Define the function to remove outliers using IQR for the specified column
def remove_outliers_iqr(data, column):
    Q1 = data[column].quantile(0.25)
    Q3 = data[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    return data[(data[column] >= lower_bound) & (data[column] <= upper_bound)]

# Remove outliers from the specified column using IQR
data = remove_outliers_iqr(data, column_to_analyze)

# Print the dataset without outliers in the specified column
print("Dataset without outliers in", column_to_analyze, ":\n", data)

In [ ]:
data.describe()

In [ ]:
data.head()

## Visulization and Analysis

In [ ]:
mileage = data['Mileage']
prod_year = data['Prod. year']

# Create a scatter plot
plt.scatter(prod_year, mileage)
plt.xlabel('Prod. year')
plt.ylabel('Mileage')
plt.title('Relationship between Mileage and Prod. year')
plt.show()

In [ ]:
prod_year = data['Prod. year']
price = data['Price']

# Create a scatter plot
plt.scatter(prod_year, price)
plt.xlabel('Prod. year')
plt.ylabel('Price')
plt.title('Relationship between Prod. year and Price')

# Calculate the correlation coefficient
correlation_coefficient = data['Prod. year'].corr(data['Price'])
print('Correlation coefficient:', correlation_coefficient)

# Add the correlation coefficient to the plot
plt.text(0.1, 0.9, f'Correlation: {correlation_coefficient:.2f}', transform=plt.gca().transAxes)

# Show the plot
plt.show()

In [ ]:
data = data[data['Prod. year'] >= 2000]


In [ ]:
sns.heatmap(data.corr(),annot=True)

In [ ]:
sns.set(rc={'figure.figsize':[10,10]},font_scale=0.9)

sns.countplot(y='Manufacturer',data=data)

In [ ]:
sns.boxplot(x='Price',data=data)

In [ ]:
sns.kdeplot(data=data['Cylinders'], shade=True)

In [ ]:
sns.scatterplot(x=data['Mileage'], y=data['Price'])

# Machine learning

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

selected_features = ['Prod. year', 'Mileage', 'Engine volume', 'Cylinders', 'Doors','Airbags' ,'has_turbo' ]
X = data[selected_features]
y = data['Price']


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)

print('Train Set Score:', model.score(X_train, y_train))
print('Test Set Score:', model.score(X_test, y_test))

## 1-What is the maximum price of a car in the dataset?

In [ ]:
max_price = data['Price'].max()
print("Maximum price of a car:", max_price)


## 2-What is the minimum price of a car in the dataset?

In [ ]:
min_price = data['Price'].min()
print("Minimum price of a car:", min_price)


## 3-What is the average price of cars in the dataset?

In [ ]:
avg_price = data['Price'].mean()
print("Average price of cars:", avg_price)


## 4-How many cars have leather interior?

In [ ]:
num_cars_with_leather = len(data[data['Leather interior'] == 'Yes'])
print("Number of cars with leather interior:", num_cars_with_leather)


## 5-What is the most common category of cars in the dataset?

In [ ]:
most_common_category = data['Category'].mode()[0]
print("Most common category of cars:", most_common_category)


## 6- What is the least common category of cars in the dataset?

In [ ]:
least_common_category = data['Category'].value_counts().idxmin()
print("Least common category of cars:", least_common_category)


## 7- What is the average mileage of cars in the dataset?

In [ ]:
avg_mileage = data['Mileage'].mean()
print("Average mileage of cars:", avg_mileage)
## 6- 


## 8- What is the maximum engine volume in the dataset?

In [ ]:
max_engine_volume = data['Engine volume'].max()
print("Maximum engine volume:", max_engine_volume)


## 9-What is the maximum levy of a car in the dataset?

In [ ]:
max_levy = data['Levy'].max()
print("Maximum levy of a car:", max_levy)


## 10-What is the min levy of a car in the dataset?

In [ ]:
min_levy = data['Levy'].min()
print("Minimum levy of a car:", min_levy)


## 11-What is the average levy of cars in the dataset?

In [ ]:
avg_levy = data['Levy'].mean()
print("Average levy of cars:", avg_levy)


## 12-What is the most common manufaeturer of cars in the dataset?

In [ ]:
most_common_manufacturer = data['Manufacturer'].mode()[0]
print("Most common manufacturer of cars:", most_common_manufacturer)


## 13-What is the least common manufaeturer of cars in the dataset?

In [ ]:
least_common_manufacturer = data['Manufacturer'].value_counts().idxmin()
print("Least common manufacturer of cars:", least_common_manufacturer)


## 14-What is the most common model of cars in the dataset?

In [ ]:
most_common_model = data['Model'].mode()[0]
print("Most common model of cars:", most_common_model)


## 15-What is the least common model of cars in the dataset?

In [ ]:
least_common_model = data['Model'].value_counts().idxmin()
print("Least common model of cars:", least_common_model)


## 16-What is the most common wheel of cars in the dataset?

In [ ]:
most_common_wheel = data['Wheel'].mode()[0]
print("Most common wheel of cars:", most_common_wheel)


## 17-What is the most common wheel of cars in the dataset?

In [ ]:
most_common_color = data['Color'].mode()[0]
print("Most common color of cars:", most_common_color)


## 18-What is the least common model of color in the dataset?

In [ ]:
least_common_color = data['Color'].value_counts().idxmin()
print("Least common color of cars:", least_common_color)


## 19-What is the average airbags of cars in the dataset?

In [ ]:
avg_airbags = data['Airbags'].mean()
print("Average airbags of cars:", avg_airbags)


## 20-What is the most common fuel type of color in the dataset?

In [ ]:
most_common_fuel_type = data['Fuel type'].mode()[0]
print("Most common fuel type of cars:", most_common_fuel_type)


## 21-What is the least common fuel type of color in the dataset?

In [ ]:
least_common_fuel_type = data['Fuel type'].value_counts().idxmin()
print("Least common fuel type of cars:", least_common_fuel_type)


## 22-What is the average mileage of cars in the dataset?

In [ ]:
avg_mileage = data['Mileage'].mean()
print("Average mileage of cars:", avg_mileage)


## correlations between engine volem and price

In [ ]:
engine_price_corr = data['Engine volume'].corr(data['Price'])
if engine_price_corr<0 :
 print("Correlation between engine volume and price: is negitev correlation")
if engine_price_corr>0 :
 print("Correlation between engine volume and price: is postiev correlation")


## correlations between cylinder and price

In [ ]:
year_price_corr = data['Prod. year'].corr(data['Price'])

if year_price_corr<0 :
 print("Correlation between production year and price: is negitev correlation")
if year_price_corr>0 :
 print("Correlation between production year and price: is postiev correlation")


## correlations between airbagr and price

In [ ]:
turbo_price_corr = data['has_turbo'].corr(data['Price'])
if turbo_price_corr<0 :
 print("Correlation between turbo and price: is negitev correlation")
if turbo_price_corr>0 :
 print("Correlation between turbo and price: is postiev correlation")

## correlations between drive whells and price

In [ ]:
mile_price_corr = data['Mileage'].corr(data['Price'])
if mile_price_corr<0 :
 print("Correlation between mileage and price: is negitev correlation")
if mile_price_corr>0 :
 print("Correlation between mileage and price: is postiev correlation")

## correlations between gear box and price 

In [ ]:
engine_cylinders_corr = data['Engine volume'].corr(data['Cylinders'])
if engine_cylinders_corr<0 :
 print("Correlation between engine volume and cylinders:: is negitev correlation")
if engine_cylinders_corr>0 :
 print("Correlation between engine volume and cylinders:: is postiev correlation")

## correlations between mile and price 

In [ ]:
mile_year_corr = data['Mileage'].corr(data['Prod. year'])
if mile_year_corr<0 :
 print("Correlation between mileage and production year: is negitev correlation")
if mile_year_corr>0 :
 print("Correlation between mileage and production year: is postiev correlation")

## What is the most common girbox in the dataset?

In [ ]:
most_common_gearbox = data['Gear box type'].mode()[0]
print("Most common gearbox type:", most_common_gearbox)


## What is the least common girbox in the dataset

In [ ]:
least_common_gearbox = data['Gear box type'].value_counts().idxmin()
print("Least common gearbox type:", least_common_gearbox)


## What is the most common drive wheels  in the dataset?

In [ ]:
most_common_drive_wheels = data['Drive wheels'].mode()[0]
print("Most common drive wheels:", most_common_drive_wheels)


## What is the least common drive wheels in the dataset?

In [ ]:
least_common_drive_wheels = data['Drive wheels'].value_counts().idxmin()
print("Least common drive wheels:", least_common_drive_wheels)


## What is the average engine volume of cars with 4 cylinders?

In [ ]:
avg_engine_volume_4_cyl = data[data['Cylinders'] == 4]['Engine volume'].mean()
print("Average engine volume of cars with 4 cylinders:", avg_engine_volume_4_cyl)


## How many cars have a price higher than the average price in the dataset?

In [ ]:
num_cars_above_avg_price = len(data[data['Price'] > avg_price])
print("Number of cars with a price higher than the average:", num_cars_above_avg_price)


## What is the average price of cars with a fuel type of 'Hybrid'?

In [ ]:
avg_price_hybrid = data[data['Fuel type'] == 'Hybrid']['Price'].mean()
print("Average price of cars with a fuel type of 'Hybrid':", avg_price_hybrid)


## What is the average price of cars produced after the year 2015?

In [ ]:
avg_price_after_2015 = data[data['Prod. year'] > 2015]['Price'].mean()
print("Average price of cars produced after the year 2015:", avg_price_after_2015)


## How many cars have a price between $10,000 and $20,000?

In [ ]:
num_cars_between_10k_20k = len(data[(data['Price'] >= 10000) & (data['Price'] <= 20000)])
print("Number of cars with a price between $10,000 and $20,000:", num_cars_between_10k_20k)


## What is the average mileage of cars produced in the year 2018?

In [ ]:
avg_mileage_2018 = data[data['Prod. year'] == 2018]['Mileage'].mean()
print("Average mileage of cars produced in the year 2018:", avg_mileage_2018)


## What is the average price of cars with a 'Category' value of 'Sedan'?

In [ ]:
avg_price_sedan = data[data['Category'] == 'Sedan']['Price'].mean()
print("Average price of cars with a 'Category' value of 'Sedan':", avg_price_sedan)


## How many cars have a 'Levy' value greater than 1500?

In [ ]:
num_cars_levy_gt_1500 = len(data[data['Levy'] > 1500])
print("Number of cars with a 'Levy' value greater than 1500:", num_cars_levy_gt_1500)


## What is the average price of cars with a 'Drive wheels' value of '4x4'?

In [ ]:
avg_price_4x4 = data[data['Drive wheels'] == '4x4']['Price'].mean()
print("Average price of cars with a 'Drive wheels' value of '4x4':", avg_price_4x4)


## What is the most common manufacturer for cars with a 'Category' value of 'Hatchback'?

In [ ]:
most_common_manufacturer_hatchback = data[data['Category'] == 'Hatchback']['Manufacturer'].mode()[0]
print("Most common manufacturer for cars with a 'Category' value of 'Hatchback':", most_common_manufacturer_hatchback)


## What is the average price of cars with a 'Model' value of 'Corolla'?

In [ ]:
avg_price_corolla = data[data['Model'] == 'Corolla']['Price'].mean()
print("Average price of cars with a 'Model' value of 'Corolla':", avg_price_corolla)


## What is the average mileage of cars with a 'Category' value of 'jeep'?

In [ ]:
avg_mileage_jeep = data[data['Category'] == 'jeep']['Mileage'].mean()
print("Average mileage of cars with a 'Category' value of 'jeep':", avg_mileage_jeep)


## What is the average price of cars with a 'Manufacturer' of 'Lexus' and 'Engine volume' greater than 3.5?

In [ ]:
avg_price_lexus_engine_gt_3_5 = data[(data['Manufacturer'] == 'Lexus') & (data['Engine volume'] > 3.5)]['Price'].mean()
print("Average price of cars with a 'Manufacturer' of 'Lexus' and 'Engine volume' greater than 3.5:", avg_price_lexus_engine_gt_3_5)


## How many cars have a 'Category' of 'Hatchback' and 'Airbags' greater than 4?

In [ ]:
num_cars_hatchback_airbags_gt_4 = len(data[(data['Category'] == 'Hatchback') & (data['Airbags'] > 4)])
print("Number of cars with a 'Category' of 'Hatchback' and 'Airbags' greater than 4:", num_cars_hatchback_airbags_gt_4)


## What is the average mileage of cars with a 'Manufacturer' of 'Honda' and 'Model' of 'Civic'?

In [ ]:
avg_mileage_honda_civic = data[(data['Manufacturer'] == 'Honda') & (data['Model'] == 'Civic')]['Mileage'].mean()
print("Average mileage of cars with a 'Manufacturer' of 'Honda' and 'Model' of 'Civic':", avg_mileage_honda_civic)


## How many cars have a 'Manufacturer' of 'Ford' and 'Airbags' less than or equal to 4?

In [ ]:
num_cars_ford_airbags_lte_4 = len(data[(data['Manufacturer'] == 'Ford') & (data['Airbags'] <= 4)])
print("Number of cars with a 'Manufacturer' of 'Ford' and 'Airbags' less than or equal to 4:", num_cars_ford_airbags_lte_4)


In [ ]:
data.to_csv('car_price_prediction.csv', index=False)

In [137]:
# data['Price'] = data['Price'] 
# price_mean =data['Price'].mean()
# Levy_mean

# def price(a):
#         if(a<11000):
#             return data['Price'].mean()
#         else:
#             return(a)
    
# price(1)    

#  data['Price'] = data['Price'].apply(price)
    
    
# #import libraries
# import numpy as np
# mean = np.mean(data['Price'])
# std = np.std(data['Price'])
# print('mean of the price is', mean)
# print('std. deviation is', std)
# threshold = 3
# outlier = []
# for i in data['Price']:
#     z = (i-mean)/std
#     if z > threshold:
#         outlier.append(i)
# print('outlier in dataset is', outlier)